### PR TITLE
Disables tests in the PM due to layout problems

### PR DESCRIPTION
**Pull request by hpux735**
Hi!

I love using PMJSON, but I had to fork it to use it with the Swift package manager.  The problem is that the structure of the Tests directory is non-compliant with the PM.  Would you be interested in addressing it?

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/postmates/pmjson/9)

### CODE REVIEW

**Comment by kballard** [comment]
Hmm, looks like it's not actually possible to make it compliant, because the tests rely on fixture files and SwiftPM doesn't seem to have a way to support those.

**Comment by hpux735** [comment]
Yah, it kinda sucks.  That's why this PR just excludes that directory from SwiftPM.

**Comment by kballard** [comment]
Thanks for the PR!

**Comment by hpux735** [comment]
Sure, thanks for PMJSON! 😁

**Pull request merged**
