### PR TITLE
Update tests to reflect latest SwiftCheck changes for Swift 3.0

### PR DESCRIPTION
**Pull request by otanistudio**
This change is [Reviewable](https://reviewable.io/reviews/postmates/pmjson/6)

### CODE REVIEW

**Comment by kballard** [comment]
Thanks for the PR! Xcode 8 beta 6 just came out today with some significant changes to Swift, so I'm going to hold off on this until I have the time to update PMJSON for beta 6 (and presumably SwiftCheck will need updates too, so we have to give them time).

**Comment by otanistudio** [comment]
Finally had a chance to look at Xcode 8 beta 6 and indeed there's much more now to change so this PR is now really behind the times! I'll need to close this and if there's time to get all the dependencies and changes in, I'll open another PR.

**Comment by kballard** [comment]
I just pushed the appropriate changes.

**Comment by otanistudio** [comment]
Thank you @kballard 😄

**Pull request closed without merging**
