### PR TITLE
Support swift package manager

### PR DESCRIPTION
**Pull request by hpux735**

### CODE REVIEW

**Comment by kballard** [comment]
Good idea, but the commit name shouldn't have "WIP" in it, and if I'm going to add Swift Package Manager support, I should go ahead and also make the package work on Linux.

**Comment by hpux735** [comment]
I didn't actually want to submit this yet 😕.  I'm planning on working with this on Linux, so maybe I'll be able to make inroads on that front.  Want me to close it?

**Comment by kballard** [comment]
Sure, go ahead and close it. I'm just going to throw some `#if os()` checks around the Foundation bits and commit that, and then if I get Swift running on my Linode I'll be able to test it.

**Comment by hpux735** [comment]
Cool.  Thanks :)

**Comment by kballard** [comment]
Swift Package Manager support added in 79216175806eb25f91ccb93ef455fba20b027e1a, and Linux support added in 3701fdadd71aa26445c62e013145536ee7d3d648.

**Comment by hpux735** [comment]
😀 Awesome!

**Pull request closed without merging**
